### PR TITLE
Add camera calibration chapter

### PR DESCRIPTION
**Pull request by MankaranSingh**
Added extrinsic camera calibration chapter.

### CODE REVIEW

**Comment by thomasfermi** [comment]
Hey @MankaranSingh , thanks for this pull request! I think that this is a great first draft. But there are several things that would need to be addressed before I would like to merge this to the master branch. I am going to list those issues below. 

1. There is currently no "test" jupyter notebook under `code/tests` like it's the case for the other chapters
2. The video for the exercise should be from a highway in Carla, not from an urban intersection. The "test" jupyter notebook should have code that reads in the video file, and displays some images of the video. It should then also display the detected lane lines, and the determined vanishing point.
3. I do not like hand-coded coordinates for the lane lines. The chapter should import the neural network from the lane detection chapter to get the lane lines. For this `lane_detector.py` would need to be adapted slightly. This could be even part of the exercise: "Adapt the lane_detector class, such that it determines a lane line v(u) = c0 + c1* u from an image". In the book chapter, the solution to that exercise would be imported.
4. There  should be a section which explains how you get a rotation matrix from roll pitch and yaw.
5. There needs to be a discussion section at the end, which also mentions how comma.ai solves the calibration problem.
6. Instead of a new file `code/util/camera_util.py`, the file `code/solutions/lane_detection/camera_geometry.py` should be used to import the `get_intrinsic_matrix()` function
7. There should be references.  For example the image from wikipedia should get credit. I think that the equations which determine yaw and pitch are based on some Coursera course. This (or even better some orginal book or paper) should be cited.
8. Some symbols are bold that should not be. Some sentences could be worded differently. I could make a detailed review in that regard if the other points are adressed.
9. You need to be added as author in the `book/_config.yml`
10. The introduction page needs to be adapted so that it mentions the new chapter.

My proposal is the following: I can create a new branch "CameraCalibration" for this original repo, which will not contain any new code for now. You can work on 0 - 100% of the issues. Once you have done this, you make a new pull request which you merge into the "CameraCalibration" branch. I will accept that pull request (even if you choose to adress 0% of the issues).
Then I will address the remaining issues using the "CameraCalibration" branch (this could take several weeks/months), and once I am happy, I will merge it into the master branch, and the web page will show the new chapter. 
You would have to live with me making changes to the content you created. If there is something you do not like we could of course always discuss it :)

What do you think?

**Comment by MankaranSingh** [comment]
Hi @thomasfermi . The suggested changes are good. Have some questions regarding the 3rd and 9th point. 

3) tbh, I have not worked with the lane detection model of this book. I think it would be a lot faster if you could provide a sample code which I can work upon while I work on other issues. 

9) I cannot seem to find a way to add multiple authors in the book. if it's not possible, maybe we can just mention chapter writer's name at top of the chapter ? maybe we can also add something for the contributors too (ones who havent written a page but made changes or improved the page). 

thanks !
~Mankaran

**Comment by thomasfermi** [comment]
Hi @MankaranSingh ! 

Regarding 3) Of course I can do that!

Regarding 9) It should be possible. Have a look at this [_config.yml from the quantecon-mini-example book](https://github.com/executablebooks/quantecon-mini-example/blob/master/mini_book/_config.yml). In the second line they give two authors. Regarding adding something for contributors: I could add a contributors.md in the github repo and mention it in the book maybe. Will think about it.

I created a new branch CameraCalibrationDev. Would you please create a pull request with the same content as this one here, but aimed at the CameraCalibrationDev branch? Then we can both work together on that branch. The stuff I would prepare regarding 3), I could commit it to the branch.

**Comment by thomasfermi** [comment]
Hi @MankaranSingh ! Short update:

I updated the master branch to work with the newest jupyter book version.

I added files to the CameraCalibrationDev branch:
* [test notebook](https://github.com/thomasfermi/Algorithms-for-Automated-Driving/blob/CameraCalibrationDev/code/tests/camera_calibration/calibration.ipynb)
* [solution code](https://github.com/thomasfermi/Algorithms-for-Automated-Driving/blob/CameraCalibrationDev/code/solutions/camera_calibration/camera_calibrator.py)

This is just a minimal version for now.

**Comment by MankaranSingh** [comment]
Wow, thanks for making those files ! You can leave the rest on me. I'd make all the changes and make a new pull request as soon as possible.

**Comment by thomasfermi** [comment]
Ok, I am closing this pull request then. Looking forward to the new one :)

**Pull request closed without merging**
